spring.application.name=sistemadegestiondepedidos

# Configuración de la Base de Datos Oracle Cloud (Producción)
spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gb573ddc9134ef1_inscriptionsystem_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ADMIN
spring.datasource.password=Alexander1214*

# Configuración obligatoria del Driver y Dialecto
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración AWS
aws.s3.bucket-name=sistema-de-gestios-de-pedidos-diaz
aws.region=us-east-1
# Credenciales (se recomienda usar variables de entorno en el servidor real)
# Credenciales dinámicas desde las variables del contenedor Docker
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}

# Ruta para el EFS (montaje temporal en EC2)
efs.mount-path=/mnt/efs/guias

# El emisor que te validó AWS
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/771f56a3-985f-4d1b-b1bd-ccfff9b86a57/v2.0

# La URL de las llaves públicas (JWK Set URI)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/771f56a3-985f-4d1b-b1bd-ccfff9b86a57/discovery/v2.0/keys
